server:
  port: 8045
spring:
  application:
    name: springcloud-eureka
eureka:
  client:
    register-with-eureka: true # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://eureka1:8043/eureka,http://eureka2:8044/eureka
  instance:
    hostname: eureka3